### ISSUE TITLE
[FEAT] Add support for version ranges.

### ISSUE THREAD

**Issue by waynebrantley** [Appsweet-co/npm-carbon#12]
Do not need to copy every version of a package that ever existed.
Maybe just version 6 and later or something.
Perhaps just support the same syntax as package.json supports so like:
"^6" or "^17 || ^18"

**Comment by dperuo** [comment]
@waynebrantley - Added range support in https://github.com/Appsweet-co/npm-carbon/pull/16

I published a release candidate to npm. Would you mind updating to `v1.1.0-rc.0` and see what you think?

https://www.npmjs.com/package/@appsweet-co/npm-carbon

**Comment by waynebrantley** [comment]
LTGM seemed to work.
I was trying to clone @organization/project into github repo but it is not happy because of the organization tag.  Any ideas?

**Comment by dperuo** [comment]
> LTGM seemed to work. I was trying to clone @organization/project into github repo but it is not happy because of the organization tag. Any ideas?

@waynebrantley - There may be limits set by GitHub. I don't see anything in the source code for npm-carbon that would get in the way of organization tags.
