### ISSUE TITLE
[FIX] 404 error copying packages from Nexus to CodeArtifact

### ISSUE THREAD

**Issue by hydeenoble** [Appsweet-co/npm-carbon#9]
**Describe the bug**
I am trying to use this tool to copy scoped packages existing in nexus registry to codeartifact but I keep getting 404 when it trys to reference the package on codeartifact (to get the existing versions there) 

**To Reproduce**
1. Get token for codeartifact
2. Get token for Nexus registry
3. Run `npx @appsweet-co/npm-carbon` command with the following flags: 
    * --src
    * --srcToken
    * --dest
    * --destToken
 4. I get the error message: 
```
[INFO] ℹ️  Getting versions from source...
info attempt registry request try #1 at 12:52:01 PM
http request GET http://nexus-registry//@scope/package
http 200 http://nexus-registry//@scope/package
[INFO] ℹ️  Getting versions from destination...
info attempt registry request try #1 at 12:52:01 PM
http request GET https://codeartifact-registry//@scope/package
http 404 https://codeartifact-registry//@scope/package
/path/to/nvm/.nvm/versions/node/v14.21.1/lib/node_modules/@appsweet-co/npm-carbon/bin/service.js:86
                        resolve(data.versions);
                                     ^

TypeError: Cannot read property 'versions' of null
```
**Expected behavior**
This command is supposed to copy packages from Nexus to CodeArtifact

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome
 - Version 1.0.12
 - Node Version: v14.21.1

**Comment by dperuo** [comment]
@hydeenoble - Sorry for the delay. Please upgrade to [v1.0.13](https://www.npmjs.com/package/@appsweet-co/npm-carbon/v/1.0.13) and try again.

(Fixed in https://github.com/Appsweet-co/npm-carbon/commit/7065cda8e370ce10b3ea888b50f55eab40cc080b)

**Comment by hydeenoble** [comment]
Thanks for your response.

**Comment by dperuo** [comment]
@hydeenoble - I marked this issue as DONE. Please open a new issue if needed.
